from extended_tfp.layers.conv_variational_v2 import Conv2DVariational
from extended_tfp.layers.attention_variational import AttentionVariational
from extended_tfp.layers.attention_variational import SelfAttentionVariational
from extended_tfp.layers.utils import posterior_mean_field
from extended_tfp.layers.utils import prior_trainable
